Use the following code for the questions below:

In [92]:
import numpy as np #industry standard

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

1. How many negative numbers are there?


In [93]:
num_negative = np.sum(a < 0) #uses the sum function together wanting only those less than 0
                        # notice that it doesn't add these 4 negative numbers
num_negative

4

In [94]:
# example for fun # If I was to want the 4 negatives to be sumed up #

negative_numbers = a[a < 0] #returns the negative numbers only (4 of them)

sum_of_negatives = np.sum(negative_numbers)

print(negative_numbers)
print(sum_of_negatives)

[-2 -1 -6 -7]
-16


2. How many positive numbers are there?


In [95]:
num_positive = np.sum(a > 0)

num_positive

5

In [100]:
(a > 0).sum() # Trues have a value of 1

5

3. How many even positive numbers are there?

In [28]:
even_positive = a[(a > 0) & (a % 2 == 0)]

print(even_positive)
len(even_positive)

[ 4 10 12]


3

In [31]:
# another simple way ex.
even_positive_2 = np.sum((a > 0) & (a % 2 == 0))
even_positive_2

3

4. If you were to add 3 to each data point, how many positive numbers would there be?


In [38]:
a_plus_3 = a + 3
print(a_plus_3) # printing all 12 with the added 3


num_positive_plus_3 = np.sum(a_plus_3 > 0) # counting only the 10 positive numbers
num_positive_plus_3

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


10

In [103]:
((a + 3) > 0).sum() # Counts the Trues

10

5. If you squared each number, what would the new mean and standard deviation be?


In [43]:
a_squared = a ** 2

print(a_squared)
print()
print(np.mean(a_squared))
print(np.std(a_squared))

[ 16 100 144 529   4   1   0   0   0  36   9  49]

74.0
144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.


In [104]:
print(a)
print(np.mean(a))
print()

a_centered = a - 3
print(np.mean(a_centered))
a_centered

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
3.0

0.0


array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

7. Calculate the z-score for each data point. Recall that the z-score is given by: (known as standardizing)

Z = (x − μ) / σ

$\mu$ = Mean

$\sigma$ = Standard Deviation

In [106]:
print(np.mean(a))
print(np.std(a))
print()
a_z_score = (a - (np.mean(a))) / (np.std(a))

print(a_z_score)

# This is now a standard normal distribution, where it is centered (mean is 0) and the
# Std is 1.

# To go back to a normal distribution, multiply Std then add the mean.
# (which will give the original array)

3.0
8.06225774829855

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


## 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [108]:
import numpy as np
# Life w/o numpy to life with numpy

In [109]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [110]:
sum_of_a = sum(a)
# sum_of_a = np.sum(a) # using numpy to call functijons
sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [111]:
min_of_a = min(a)
# min_of_a = np.min(a) # using numpy to call functijons
min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [112]:
max_of_a = max(a)
# max_of_a = np.max(a)
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [113]:
mean_of_a = sum(a) / len(a)
# mean_of_a = np.mean(a)
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [115]:
product_of_a = 1

for i in a:
    product_of_a *= i
    
# product_of_a = np.product(a) # using numpy
product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [88]:
squares_of_a = [n**2 for n in a] 
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [116]:
square_of_a = []

for i in a :
    squares_of_a.append(i**2)
    
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [121]:
odds_in_a = []

for i in a:
    if i % 2 == 1:
#         print(i)
        odds_in_a.append(i)
        
odds_in_a

[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [124]:
evens_in_a = []

for i in a:
    if i % 2 == 0:
#         print(i)
        evens_in_a.append(i)

evens_in_a

# completed all 8 above using built-in function NOT from numpy (classic way)

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product,  and list of squares for this list of two lists.

In [ ]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [125]:
b = np.array(b)

In [ ]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [126]:
np.sum(b)

33

In [127]:
b.sum()

33

In [128]:
sum(b) # adding each column together but not what we want, this is the NON-numpy way

array([ 9, 11, 13])

In [129]:
sum(sum(b)) # Does give the result and is the NON-numpy way

33

In [ ]:
# Exercise 2 - refactor the following to use numpy. 

In [ ]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [130]:
np.min(b)

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [ ]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [133]:
np.max(b)

8

In [ ]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [134]:
np.mean(b)

5.5

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all 

In [ ]:
# numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [135]:
np.prod(b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [137]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [136]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [138]:
b [b % 2 == 1]

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [139]:
b [b % 2 == 0]

array([4, 6, 8])

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [141]:
b 

array([[3, 4, 5],
       [6, 7, 8]])

In [140]:
b.shape # rows vs columns

(2, 3)

#### Exercise 10 - transpose the array b.

In [142]:
np.transpose(b) #numpy function

array([[3, 6],
       [4, 7],
       [5, 8]])

In [143]:
np.transpose(b).shape

(3, 2)

In [144]:
b.T #method

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [145]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [146]:
np.reshape(b, (1,6)) #numpy function

array([[3, 4, 5, 6, 7, 8]])

In [147]:
b.flatten() #object

array([3, 4, 5, 6, 7, 8])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [148]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [150]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.

In [151]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Exercise 1 - Find the min, max, sum, and product of c.

In [152]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

#### Exercise 2 - Determine the standard deviation of c.

In [155]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [154]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [156]:
c.shape #attribute #doesn't need parenthesis

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [157]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c. 

In [159]:
np.dot(c, c) # dot product is more than just multiplying itself (involves magnitude... and stuff)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [163]:
(c.T * c)

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [162]:
(c.T * c).sum()

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
Answer should be 131681894400.

In [164]:
(c.T * c)

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [165]:
(c.T * c).prod()

131681894400

## Setup 4

In [183]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [184]:
d = np.array(d)

#### Exercise 1 - Find the sine of all the numbers in d

In [185]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [186]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [187]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [188]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [189]:
d [d < 0]

array([-90, -30, -45, -45])

#### Exercise 5 - Find all the positive numbers in d

In [190]:
d [d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### Exercise 6 - Return an array of only the unique numbers in d.

In [191]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [193]:
len(np.unique(d)) # The way to go!

11

In [192]:
np.count_nonzero(np.unique(d)) # doesn't work here because for some reason, the function doesn't include 0

10

#### Exercise 8 - Print out the shape of d.

In [194]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [195]:
d.shape #rows vs columns

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [198]:
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [197]:
d.T.shape

(6, 3)

#### Exercise 10 - Reshape d into an array of 9 x 2

In [199]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [200]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])